### ISSUE TITLE
[Feature Request] Auto-hide members list when resized small

### ISSUE THREAD

**Issue by burritosoftware** [j0lol/Scalable-Discord#1]
Basically the title, when Discord is resized small the members list should automatically hide away

**Comment by j0lol** [comment]
i can try that! the members list is still somewhat usable at lower resolutions but it might make sense to hide it when resolution turns smaller? im not really sure how to hook into that sorta stuff im not a react dev

what do you think? i dont really use the list that much

**Comment by burritosoftware** [comment]
I use the list on desktop and mobile frequently but I think the way it should work is like how you do with the channel list: autohide it on small, and then you can click the icon to open it fullscreen and click it again to hide it away (but it doesnt change the internal setting! this is crucial) after which if you resize back to big the members list will reappear if you kept it open in "desktop mode"

this makes it emulate the mobile behavior

**Comment by j0lol** [comment]
this shouldnt be that hard, ill work on it

**Comment by j0lol** [comment]
working on this further at #5
