### ISSUE TITLE
Channel tray no longer collapses

### ISSUE THREAD

**Issue by EmeraldSnorlax** [j0lol/Scalable-Discord#8]
When shrinking a window, the tray pops out and expands to cover the whole window.
I'm not sure what changed (no commit was made for a while), but now after clicking a channel the tray no longer collapses. The new guild or channel is active, but the tray still covers the window.

https://user-images.githubusercontent.com/43452521/126604641-41b57ed6-1fdd-4ca9-808c-9da675c27ebc.mp4

```
Canary 90820 (467ab66)
Host 0.0.126
Linux 64-Bit (5.12.15-Arch1-1)
```

I can't seem to find it in the UI, so here is the latest git commit on `main`

```
Commit: def1baa9c772c625589c6150a2c0087588af11c3
Parents: 90bf8852c6a486ce7b985ec74d6343fd7b36439e
Author: jo! <jo@pop-os.local>
Committer: jo! <jo@pop-os.local>
Date: Wed Mar 31 2021 23:19:44 GMT+0100 (British Summer Time) 

increment version number, woo
```

**Comment by j0lol** [comment]
weird behavior, not sure what went wrong here
ill look into it soon

**Comment by EmeraldSnorlax** [comment]
just wanted to add on that there seems to be another quirk: the tray collapses normally when selecting a person from the dm list. this bug seems to be limited to collapsing the channel list in guilds only

**Comment by EmeraldSnorlax** [comment]
well, im not really sure what changed but as of now (`Canary 91437 (65b36a8)`) it seems to working as intended again

**Comment by j0lol** [comment]
well then,, lol
